seed: 9

run_notes: KObj_Change_curriculum_rollout3

model_base_path: null  # Folder to load the model from
model_checkpoint: null  # Model checkpoint zip file name (without .zip) to load
teacher:
#  path: toy_teacher/rl_train_logs/2024-11-21-151501_map=map_rl=ppo-epochs=10-eplen=100_s=9_nt=None/checkpoint  # Folder to load the model from
  path: ./toy_static
  checkpoint: RL_model_Level1  # Model checkpoint zip file name (without .zip) to load

compute:
  n_gpu_workers: 1
  n_cpu_workers: 8  # One gym env per cpu

logging:
  log_freq: 300  # How many times to log during training
  video_save_freq: 20000 # Frequency to save the video
  model_save_freq: 100000  # Frequency to save the model

  wandb_project: toy
  wandb_mode: online
  wandb_tags: []

  run_name: null
  run_path: null

env:
  example_name: empty_map3
#  example_name: student_failed_map
#  example_name: map_realizability3
  episode_length: 100
  include_history: false
  curriculum: 0
  num_obj: 5

bc_algo:
  name: dagger
  visibility: occluded
  total_episode: 20
  aug_episode: 30
  aug_iter: 10
  total_timestep: 100*100
  n_epochs: 100
  batch_size: 128
  gamma: 0.99
  n: null
  bc_path: null
#  bc_path: ./toy_static/train_logs/5Obj_5success/DAgger
#  pre_trained_path: toy_teacher/rl_train_logs/2024-11-21-151501_map=map_rl=ppo-epochs=10-eplen=100_s=9_nt=None/checkpoint/final_mocgdel.zip

#cost_fn: nav_shortest_path

log_folder: ./toy_static/train_logs/
log_path: ${log_folder}/${env.example_name}_visibility=${bc_algo.visibility}_${env.num_obj}Objs_nt=${run_notes}_${bc_algo.total_episode}epi_${bc_algo.n_epochs}epo__${now:%Y-%m-%d-%H%M%S}
defaults:
#  - seq_reward_model: dtw
  - _self_


hydra:
  run:
    dir: ${log_folder}/${env.example_name}_visibility=${bc_algo.visibility}_${env.num_obj}Objs_nt=${run_notes}_${bc_algo.total_episode}epi_${bc_algo.n_epochs}epo__${now:%Y-%m-%d-%H%M%S}
